module.exports = {
  SHOP: "products-nm",
  ABOUT_TITLE: "Gutes vom Gustergut seit 1324",
  ABOUT_CAPTION: "Unser Versprechen",
  CONTACT_TITLE: "Zum Gustergut – Kontakt",
  ABOUT_TEXT: [
  "Die Essenz aus der Natur.",
  "Gutes wird auf dem Gustergut schon lange gepflegt: Das sind unsere Äpfel, Birnen, Trauben und die vielen anderen Früchte und Obstsorten, aus denen wir unsere Produkte gewinnen. Jedes Obst, jede Frucht geht durch unsere Hände, denn wir pflücken zu 100 % ohne Hilfe von Maschinen. Mit viel Gespür für die Eigenschaften der Frucht wird weiter verarbeitet, gepresst, vinifziert – kurz: veredelt.",
  "Durch Professionalität in der Herstellung und mit Respekt vor dem Gewachsenen entstehen unsere Erzeugnisse am Gustergut, die Essenz aus der Natur. Das ist unser Verständnis für unsere tägliche Arbeit und das Qualitätsversprechen an unsere Kunden. Und das schmeckt man auch in unseren Produkten."
  ],
  CONTACT_ADDRESS_CAPTION: "Adresse ++ Öffnungszeiten",
  ADDRESS: ["Fruchtveredelung Geschwister Wurm", "Gustergut, Weilling 10, A‑4490 St. Florian", "+43 (0)7224 4387, office@wwurm.at"],
  OPEN_HOURS: ["wurm Hofladen am Gustergut", "Freitag 8.00 – 18.00 Uhr", "Samstag 8.00 – 12.00"],
  MAP_CAPTION: "Anreise ++ Plan",

  NAV: [
  {name: "Das Gustergut", url: "/about"},
  {name: "Kontakt", url: "/contact"}
  ],
  FOOTER_NAV: [
    { name: "Häufige Fragen", url: "/faq" },
    { name: "AGB", url: "/agb" },
    { name: "Kontakt", url: "/contact" },
  ],
  S3_ALBUM_NAME: "all-produkte",
  AWS_BUCKET_NAME: "wwurm-sydney",
  AWS_REGION: "ap-southeast-2",
  CART_KEY: "wwurm-access-key",
  SHIPPING_TITLE: "",
  DELIVERY_CAPTION: "", 
  PAYMENT_CAPTION: "", 
  EXCHANGE_CAPTION: "",
  DELIVERY: "",
  PAYMENT: "",
  EXCHANGE: "", 
  COPYRIGHT: "", 
  PRODUCTS_NAV_NAME: "Produkte",
  PRODUCTS_NAV_FIRST_NAME: "All Produkte",
  BRAND: "/wwurm/brand.svg",
  MAP_IMG: "/wwurm/map.png",
  SHIPPING_IMG: "/wwurm/about.jpg", 
  ABOUT_IMG: "/wwurm/about.jpg",
  CONTACT_IMG: "/wwurm/about.jpg",
  CAROUSEL_IMG_ARR: [ '/wwurm/img-1.jpg', '/wwurm/img-2.jpg', '/wwurm/img-3.jpg', 
    '/wwurm/img-4.jpg', '/wwurm/img-5.jpg', '/wwurm/img-6.jpg',
    '/wwurm/img-7.jpg', '/wwurm/img-8.jpg', '/wwurm/img-9.jpg'],
  LOGO: "/wwurm/logo.png",
  BRAND_WIDTH: "34%",
  BRAND_LEFT: "50%",
  BRAND_MARGIN_LEFT: "-17%",
  BRAND_TOP: "30%",
  LOAD_MORE: "Mehr laden",
  ALL_PRODUCT_LOADED: "Alle Produkte wurden geladen.",
  // common constants
  CAROUSEL_INTERVAL: 10000,
  CAROUSEL_INIT_STATE: 0,
  ICON_LIST: [
    { icon: "cm-font-heart", url: ""},
    { icon: "cm-font-facebook", url: ""},
    { icon: "cm-font-x-twitter", url: ""},
    { icon: "cm-font-pinterest", url: ""}
  ],
  CART_CLOSED_POSITION: "-410px",
  CART_OPENED_POSITION: "0px",
  CART_EMPTY_MESSAGE: "Es befinden sich keine Produkte im Warenkorb.",
  CART_CLOSE_BTN: "Schließen",
  SUBTOTAL: "Zwischensumme",
  CONTINUE_SHOPPING_BTN: "Weiter einkaufen",
  CHECKOUT_BTN: "Kasse",
  CART_PAGE_TITLE: "Warenkorb",
  CART_PAGE_SUMMARY_TITLE: "Warenkorb-Summe",
  CONTINUE_TO_CHECKOUT_BTN: "Weiter zur Kasse",
  ADD_VOUCHER: "Gutschein hinzufü­gen",
  SHIPMENT: "Versand",
  SHIPMENT_PRICE_LOCAL: "Innerhalb Berlins & Deutschlands (1–2 Tage)",
  SHIPMENT_PRICE_NATIONAL: "Versand Europaweit",
  SIMILAR_PRODUCTS: "Ähnliche Produkte",
  BUY_NOW: "Kaufen",
  REGISTER: "Anmelden",
  SIGN_OUT: "Abmelden"
}
